fragment NavigationParts on Navigation {
  __typename
  groups {
    __typename
    label
    isEnabled
    links {
      __typename
      type
      name
      page {
        ... on Pages {
          __typename
          title
          slug
          description
          template
          content
          isPublished
          createdAt
        }
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
      }
      externalUrl
      description
    }
  }
}

fragment IntentionsParts on Intentions {
  __typename
  title
  isActive
  startDate
  description
  days {
    __typename
    day
    intentions {
      __typename
      hour
      intention
    }
  }
}

fragment GalleryParts on Gallery {
  __typename
  title
  albums {
    __typename
    albumTitle
    description
    images {
      __typename
      src
      caption
      alt
    }
  }
}

fragment ContactParts on Contact {
  __typename
  title
  description
  googleMapsUrl
  contactItems {
    __typename
    label
    description
    value
  }
}

fragment PagesParts on Pages {
  __typename
  title
  slug
  description
  template
  content
  isPublished
  createdAt
}
